version: "3.8"

services:
  vault-filesystem:
    build:
      context: .
      dockerfile: Dockerfile.file
    image: shrish/vault-filesystem:0.1
    container_name: my_vault
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
